-- 1. Crea la tabella per le impostazioni del Bar
CREATE TABLE bar_settings (
    id bigint generated by default as identity primary key,
    bar_name text,
    phone_number text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Inserisci i dati iniziali (Modifica questi valori se necessario)
INSERT INTO bar_settings (bar_name, phone_number)
VALUES ('Bar Ufficio', '+393881137272');


-- 3. Crea la tabella per i prodotti
CREATE TABLE products (
    id text primary key, -- Usiamo ID testuali come 'caffe', 'cappuccino' per semplicità
    name text not null,
    price numeric not null,
    category text, -- Opzionale, per future espansioni
    is_available boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Inserisci il menu iniziale
INSERT INTO products (id, name, price) VALUES
    ('caffe', '☕ Caffè', 1.2),
    ('ginseng_amaro', '☕ Ginseng Amaro', 1.5),
    ('zucchero_di_canna', '☕ Zucchero di Canna', 1.5),
    ('cappuccino', '🥛 Cappuccino', 1.5),
    ('cornetto_crema_limone', '🥐 Cornetto Crema Limone', 1.3),
    ('succo', '🧃 Succo di frutta', 1.2),
    ('te_limone', '🍵 Tè al Limone', 1.4),
    ('te_pesca', '🍵 Tè alla Pesca', 1.4);

-- 5. Abilita l'accesso in lettura (SELECT) per tutti (anon)
-- Supabase usa Row Level Security (RLS). Per semplicità, abilitiamo la lettura pubblica.

ALTER TABLE bar_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON bar_settings
    FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON products
    FOR SELECT USING (true);

-- 6. Abilita scrittura pubblica (ATTENZIONE: Solo per demo/test)
-- Permette a chiunque abbia la chiave anonima (quindi anche l'app admin) di modificare i dati.
-- La "sicurezza" è delegata solo all'accesso alla pagina admin.html protetta da password JS.

CREATE POLICY "Enable insert for all users" ON bar_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON bar_settings FOR UPDATE USING (true);

CREATE POLICY "Enable insert for all users" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON products FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON products FOR DELETE USING (true);
